name: My CICD Project
on: 
  push:
    branches: ["main"]
  workflow_dispatch: 
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/chechout@v4
    - name: install python
      uses: actions/setup-python@v5
    - name: install project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py migrate
    - name: run test command
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}
      run: python manage.py test 


