name: My CICD Project
on: 
  push:
    branches: ["main"]
  workflow_dispatch: 
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: install python
      uses: actions/setup-python@v5
    - name: install project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run test command
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}
      run: |
        python manage.py migrate
        python manage.py test 
  build:
    needs: test
    runs: ubuntu-latest
    steps:
    - name: login_to_docker
      uses: docker/login-action@v3
      with: 
        username: "ronke222"
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: push to docker hub
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ronke222/cicd:latest



